### 🐍 Nos conectamos con el fichero de Medallia y únicamente nos quedamos con los campos que nos interesan

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
df = pd.read_excel(r'Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\EXPORT PRESTACIONES.xlsx')
df['oficina'] = df['ES - Unit ID Text'].str.replace('mapfre_es_', '', regex=False)
df = df[df['ES - Touchpoint'] == 'Prestación Autos - Siniestro']
columnas = [
"ES - Client first name",
"ES - Client last name",
"Email",	
"ES - Client ID",
"ES - Phone number",
"ES - Province",
"ES - Touchpoint",
"ES - MAPFRE Santander Record",
"Export AT Description",
"ES - Unit ID Text",
"ES - Unit ID",
"Fecha de respuesta",
"ES - NPS including Corredores",
"ES - Corredores - Verbatim Comment including Corredores",
"ES - General Claim - Type of claim Code",
"ES - General Claim - Type of claim Descripction",
"ES - General Claim - Processor Code",
"ES - General Claim - Receiving center",
"ES - General Claim - Center user",
"ES - General Claim - File Number",
"ES - Auto - Number Plate",
"ES - Motivo de valoración - Auto Claim  - Corredores",
"ES - Auto Claim - Satisfaction Atention",
"ES - Auto Claim - Satisfaction Next Steps",
"ES - Auto Claim - Satisfaction Proactivity",
"ES - Auto Claim - Satisfaction Explanations",
"ES - Auto Claim - Satisfaction Assesment",
"ES - Auto Claim - Satisfaction Resolution",
"ES - Auto Claim - Satisfaction Quality",
"ES - Auto Claim - Satisfaction Repairer",
"ES - Commerce - Mapfre Entity Code",
"ES - General Claim - Processor Center",
"ES - Client Value",
"oficina",
"¿Has conseguido contactar con el cliente?",
"¿El cliente queda conforme?",
"Indique la propuesta ofrecida al asegurado"
]
df=df[columnas]
df.head()

,ES - Client first name,ES - Client last name,Email,ES - Client ID,ES - Phone number,ES - Province,ES - Touchpoint,ES - MAPFRE Santander Record,Export AT Description,ES - Unit ID Text,ES - Unit ID,Fecha de respuesta,ES - NPS including Corredores,ES - Corredores - Verbatim Comment including Corredores,ES - General Claim - Type of claim Code,ES - General Claim - Type of claim Descripction,ES - General Claim - Processor Code,ES - General Claim - Receiving center,ES - General Claim - Center user,ES - General Claim - File Number,ES - Auto - Number Plate,ES - Motivo de valoración - Auto Claim - Corredores,ES - Auto Claim - Satisfaction Atention,ES - Auto Claim - Satisfaction Next Steps,ES - Auto Claim - Satisfaction Proactivity,ES - Auto Claim - Satisfaction Explanations,ES - Auto Claim - Satisfaction Assesment,ES - Auto Claim - Satisfaction Resolution,ES - Auto Claim - Satisfaction Quality,ES - Auto Claim - Satisfaction Repairer,ES - Commerce - Mapfre Entity Code,ES - General Claim - Processor Center,ES - Client Value,oficina,¿Has conseguido contactar con el cliente?,¿El cliente queda conforme?,Indique la propuesta ofrecida al asegurado
2,Jose,Adrian Portillo,pepet1963@gmail.com,12294447,637453220.0,VALENCIA,Prestación Autos - Siniestro,No,VALENCIA,mapfre_es_8471,Delegacion Alboraya,2026-01-01 09:16:36,10,Buena atención y rapidez en todos los sentidos,P117,DAÃ‘OS PROPIOS ROBO,TRD7A,R8471,ALBORAYA (HORCHATA),522974731,8885KYF,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T0811,3.0,8471,NaN,NaN,NaN
27,Francisco,Estevez Corbacho,francisco-estevez@hotmail.com,7381270,676195532.0,MADRID,Prestación Autos - Siniestro,No,MADRID NORTE,mapfre_es_5899,Delegacion Madrid Chueca,2026-01-01 10:38:03,10,NaN,P118,DAÃ‘OS PROPIOS LUNAS,TR117,REXCO,EXTRANET DE COLABORADORES,522945906,8109JYL,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T9999,4.0,5899,NaN,NaN,NaN
29,Iban,Laperal Toquero,ibanlaperal@gmail.com,27493555,628069459.0,VIZCAYA,Prestación Autos - Siniestro,No,VIZCAYA,mapfre_es_8421,Delegacion Basauri Urb. Lehendakari Agirre,2026-01-01 10:43:39,10,NaN,P131,PAGO ASEGURADO A TERCEROS,TRD29,RSI27,SI24 EXTERNOS III (GSS),521602644,0691HGR,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T0811,2.0,8421,NaN,NaN,NaN
98,Francisco Javier,Fernandez Piña,javierfp32@hotmail.com,7659060,637195248.0,MALAGA,Prestación Autos - Siniestro,No,MALAGA,mapfre_es_8826,Oficina Marbella,2026-01-01 12:14:33,8,NaN,P131,PAGO ASEGURADO A TERCEROS,TRD4A,R8826,MARBELLA (FONTANILLA),520784007,1933KFC,Reparación de los daños,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,T0811,4.0,8826,NaN,NaN,NaN
108,Juan Jose,Olveira Sieira,juanjolveira@gmail.com,4244339,686774814.0,A CORUÑA,Prestación Autos - Siniestro,No,A CORUÑA,mapfre_es_5475,Delegacion Ribeira Rua De Lugo,2026-01-01 12:21:14,10,me repararon la luna media hora después de not...,P118,DAÃ‘OS PROPIOS LUNAS,TR117,REXCO,EXTRANET DE COLABORADORES,523058406,4558NBD,Resolución del siniestro,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,41.0,T9999,5.0,5475,NaN,NaN,NaN

In [2]:
duplicados = df["ES - General Claim - File Number"].value_counts()
duplicados[duplicados > 1]

ES - General Claim - File Number
522664971    2
523038736    2
523593619    2
523761322    2
Name: count, dtype: int64

In [24]:
encuestas = df['ES - Client ID'].count()
print(f"Total Encuestas: {encuestas}")

Total Encuestas: 7426

In [3]:
tipo_dato = df["ES - General Claim - File Number"].dtype
print(f"El tipo de dato de la columna 'ES - General Claim - File Number' es: {tipo_dato}")

El tipo de dato de la columna 'ES - General Claim - File Number' es: object

### 🐍 Nos conectamos con el fichero de Peritaciones

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
df_peritos = pd.read_csv(r'Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\NPS_Autos\Tablas\01 Peritaciones por Taller.txt', encoding="UTF-16", sep="\t")
df_peritos.head()

,Número Expediente,Código Taller,Nombre Taller,Marca Taller Distnguido,Código Provincia,Nombre Provincia,DGT Taller,Nombre Centro de Peritaciones,Nombre DGT Peritaciones,Apellidos Jefe DGT Peritaciones,Código Perito,Nombre Perito,Nombre Tipo Perito,Código Acuerdo,Nombre Acuerdo
0,0,730182,CHAPISTERIA Y GRUAS J.MONSERRAT,TD,7,ILLES BALEARS,02 Cataluña-Baleares,BALEARES,CATALUÑA-BALEARES,COMA MENDOZA,908,GUILLERMO,Perito Empleado Mapfre,NaN,NO APLICA
1,231233001,833862,"PLANCHISTERIAS GLORIAS, S.L.",TD,8,BARCELONA,02 Cataluña-Baleares,BARCELONA-BADALONA-HOSPITALET,CATALUÑA-BALEARES,COMA MENDOZA,535,FRANCISCO,Perito Empleado Mapfre,NaN,NO APLICA
2,239418102,2835215,"MAPFRE AUTOMOCION, S.A.",TD,28,MADRID,01 Madrid,ALCALA DE HENARES,MADRID,ORTEGA BOLLO,1587,ROBERTO,Perito Empleado Mapfre,NaN,NO APLICA
3,252088501,1110690,CADIMAR LOS BARRIOS,TD,11,CADIZ,08 Sur,CADIZ,SUR,FERNANDEZ FERRER,1146,FRANCISCO ANTONIO,Perito Empleado Mapfre,NaN,NO APLICA
4,261781204,841398,TALLERES MUÑOZ CABRERA,TD,8,BARCELONA,02 Cataluña-Baleares,CORNELLA-VILAFRANCA-IGUALADA-TARRAGONA,CATALUÑA-BALEARES,COMA MENDOZA,513,ALEJANDRO,Perito Empleado Mapfre,NaN,NO APLICA

### 🐍 Cruzamos la información de Medallia con la de Peritaciones

In [5]:
# Los campos de expediente los cambio a tipo string para poder cruzar la información
df['ES - General Claim - File Number'] = df['ES - General Claim - File Number'].astype(str)
df_peritos['Número Expediente'] = df_peritos['Número Expediente'].astype(str)
df_medalia_peritos = pd.merge(df, df_peritos, how='left', left_on='ES - General Claim - File Number', right_on='Número Expediente')
df_medalia_peritos.head()

,ES - Client first name,ES - Client last name,Email,ES - Client ID,ES - Phone number,ES - Province,ES - Touchpoint,ES - MAPFRE Santander Record,Export AT Description,ES - Unit ID Text,ES - Unit ID,Fecha de respuesta,ES - NPS including Corredores,ES - Corredores - Verbatim Comment including Corredores,ES - General Claim - Type of claim Code,ES - General Claim - Type of claim Descripction,ES - General Claim - Processor Code,ES - General Claim - Receiving center,ES - General Claim - Center user,ES - General Claim - File Number,ES - Auto - Number Plate,ES - Motivo de valoración - Auto Claim - Corredores,ES - Auto Claim - Satisfaction Atention,ES - Auto Claim - Satisfaction Next Steps,ES - Auto Claim - Satisfaction Proactivity,ES - Auto Claim - Satisfaction Explanations,ES - Auto Claim - Satisfaction Assesment,ES - Auto Claim - Satisfaction Resolution,ES - Auto Claim - Satisfaction Quality,ES - Auto Claim - Satisfaction Repairer,ES - Commerce - Mapfre Entity Code,ES - General Claim - Processor Center,ES - Client Value,oficina,¿Has conseguido contactar con el cliente?,¿El cliente queda conforme?,Indique la propuesta ofrecida al asegurado,Número Expediente,Código Taller,Nombre Taller,Marca Taller Distnguido,Código Provincia,Nombre Provincia,DGT Taller,Nombre Centro de Peritaciones,Nombre DGT Peritaciones,Apellidos Jefe DGT Peritaciones,Código Perito,Nombre Perito,Nombre Tipo Perito,Código Acuerdo,Nombre Acuerdo
0,Jose,Adrian Portillo,pepet1963@gmail.com,12294447,637453220.0,VALENCIA,Prestación Autos - Siniestro,No,VALENCIA,mapfre_es_8471,Delegacion Alboraya,2026-01-01 09:16:36,10,Buena atención y rapidez en todos los sentidos,P117,DAÃ‘OS PROPIOS ROBO,TRD7A,R8471,ALBORAYA (HORCHATA),522974731,8885KYF,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T0811,3.0,8471,NaN,NaN,NaN,522974731,4640408,EL XVENIR CARRERA,NO TD,46.0,VALENCIA,05 Este,ALBACETE,CENTRO,CALVO RODRIGUEZ,1251.0,JESUS PABLO,Perito Empleado Mapfre,10000045.0,GENERAL MAPFRE AUTOMOVIL
1,Francisco,Estevez Corbacho,francisco-estevez@hotmail.com,7381270,676195532.0,MADRID,Prestación Autos - Siniestro,No,MADRID NORTE,mapfre_es_5899,Delegacion Madrid Chueca,2026-01-01 10:38:03,10,NaN,P118,DAÃ‘OS PROPIOS LUNAS,TR117,REXCO,EXTRANET DE COLABORADORES,522945906,8109JYL,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T9999,4.0,5899,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Iban,Laperal Toquero,ibanlaperal@gmail.com,27493555,628069459.0,VIZCAYA,Prestación Autos - Siniestro,No,VIZCAYA,mapfre_es_8421,Delegacion Basauri Urb. Lehendakari Agirre,2026-01-01 10:43:39,10,NaN,P131,PAGO ASEGURADO A TERCEROS,TRD29,RSI27,SI24 EXTERNOS III (GSS),521602644,0691HGR,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T0811,2.0,8421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Francisco Javier,Fernandez Piña,javierfp32@hotmail.com,7659060,637195248.0,MALAGA,Prestación Autos - Siniestro,No,MALAGA,mapfre_es_8826,Oficina Marbella,2026-01-01 12:14:33,8,NaN,P131,PAGO ASEGURADO A TERCEROS,TRD4A,R8826,MARBELLA (FONTANILLA),520784007,1933KFC,Reparación de los daños,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,T0811,4.0,8826,NaN,NaN,NaN,520784007,2941268,AUTOS EUROPA,TD,29.0,MALAGA,08 Sur,MARBELLA (ROSIQUE),SUR,FERNANDEZ FERRER,2904.0,PERITACIONES,Perito Honorario,10000045.0,GENERAL MAPFRE AUTOMOVIL
4,Juan Jose,Olveira Sieira,juanjolveira@gmail.com,4244339,686774814.0,A CORUÑA,Prestación Autos - Siniestro,No,A CORUÑA,mapfre_es_5475,Delegacion Ribeira Rua De Lugo,2026-01-01 12:21:14,10,me repararon la luna media hora después de not...,P118,DAÃ‘OS PROPIOS LUNAS,TR117,REXCO,EXTRANET DE COLABORADORES,523058406,4558NBD,Resolución del siniestro,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,41.0,T9999,5.0,5475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
registros_con_peritos = df['ES - Client ID'].count()
print(f"Total Encuestas: {registros_con_peritos}")

Total Encuestas: 7426

### 🐍 Nos conectamos al fichero de Talleres

In [7]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
df_talleres = pd.read_csv(r'Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\NPS_Autos\Tablas\02 Talleres.txt', encoding="UTF-16", sep="\t")
df_talleres.head()

,Año Actual,Mes Actual,Código Taller,Código Provincia Taller,Nombre Provincia Taller,Nombre Taller,Localidad,Marca Taller Distinguido,Marca Taller Centro Servicios (S/N),Marca Taller P@P (S/N),Código Actividad Ppal,Nombre Actividad Ppal,Código Clase Ppal,Nombre Clase Ppal
0,2026,2,1120899,11,CADIZ,TALLERES MECARDI,PUERTO REAL,No Distinguido,No Centro Servicios,No Taller P@P,1.0,Chapa,4.0,GENERICO
1,2026,2,1130066,11,CADIZ,GLASSDRIVE JEREZ,JEREZ DE LA FRONTERA,Distinguido,No Centro Servicios,No Taller P@P,5.0,Lunas,4.0,GENERICO
2,2026,2,1130338,11,CADIZ,AUTOMOCION LOS REMEDIOS S.L.,VEJER DE LA FRONTERA,Distinguido,No Centro Servicios,No Taller P@P,1.0,Chapa,4.0,GENERICO
3,2026,2,1130341,11,CADIZ,MOTODEPORTE,CADIZ,No Distinguido,No Centro Servicios,No Taller P@P,1.0,Chapa,4.0,GENERICO
4,2026,2,1130603,11,CADIZ,"MECANICA CUESTA DEL RAYO,S.L.",ALGECIRAS,No Distinguido,No Centro Servicios,No Taller P@P,1.0,Chapa,4.0,GENERICO

### 🐍 Cruzamos la información de Medallia + Peritaciones con la información de Talleres por Código de Taller

In [8]:
# Asi conseguimos pegarle a la información de peritaciones los atributos específicos del taller
df_medalia_peritos_talleres = pd.merge(df_medalia_peritos, df_talleres, how='left', left_on='Código Taller', right_on='Código Taller')
df_medalia_peritos_talleres.head()

,ES - Client first name,ES - Client last name,Email,ES - Client ID,ES - Phone number,ES - Province,ES - Touchpoint,ES - MAPFRE Santander Record,Export AT Description,ES - Unit ID Text,ES - Unit ID,Fecha de respuesta,ES - NPS including Corredores,ES - Corredores - Verbatim Comment including Corredores,ES - General Claim - Type of claim Code,ES - General Claim - Type of claim Descripction,ES - General Claim - Processor Code,ES - General Claim - Receiving center,ES - General Claim - Center user,ES - General Claim - File Number,ES - Auto - Number Plate,ES - Motivo de valoración - Auto Claim - Corredores,ES - Auto Claim - Satisfaction Atention,ES - Auto Claim - Satisfaction Next Steps,ES - Auto Claim - Satisfaction Proactivity,ES - Auto Claim - Satisfaction Explanations,ES - Auto Claim - Satisfaction Assesment,ES - Auto Claim - Satisfaction Resolution,ES - Auto Claim - Satisfaction Quality,ES - Auto Claim - Satisfaction Repairer,ES - Commerce - Mapfre Entity Code,ES - General Claim - Processor Center,ES - Client Value,oficina,¿Has conseguido contactar con el cliente?,¿El cliente queda conforme?,Indique la propuesta ofrecida al asegurado,Número Expediente,Código Taller,Nombre Taller_x,Marca Taller Distnguido,Código Provincia,Nombre Provincia,DGT Taller,Nombre Centro de Peritaciones,Nombre DGT Peritaciones,Apellidos Jefe DGT Peritaciones,Código Perito,Nombre Perito,Nombre Tipo Perito,Código Acuerdo,Nombre Acuerdo,Año Actual,Mes Actual,Código Provincia Taller,Nombre Provincia Taller,Nombre Taller_y,Localidad,Marca Taller Distinguido,Marca Taller Centro Servicios (S/N),Marca Taller P@P (S/N),Código Actividad Ppal,Nombre Actividad Ppal,Código Clase Ppal,Nombre Clase Ppal
0,Jose,Adrian Portillo,pepet1963@gmail.com,12294447,637453220.0,VALENCIA,Prestación Autos - Siniestro,No,VALENCIA,mapfre_es_8471,Delegacion Alboraya,2026-01-01 09:16:36,10,Buena atención y rapidez en todos los sentidos,P117,DAÃ‘OS PROPIOS ROBO,TRD7A,R8471,ALBORAYA (HORCHATA),522974731,8885KYF,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T0811,3.0,8471,NaN,NaN,NaN,522974731,4640408,EL XVENIR CARRERA,NO TD,46.0,VALENCIA,05 Este,ALBACETE,CENTRO,CALVO RODRIGUEZ,1251.0,JESUS PABLO,Perito Empleado Mapfre,10000045.0,GENERAL MAPFRE AUTOMOVIL,2026.0,2.0,46.0,VALENCIA,EL XVENIR CARRERA,SILLA,No Distinguido,No Centro Servicios,No Taller P@P,1.0,Chapa,4.0,GENERICO
1,Francisco,Estevez Corbacho,francisco-estevez@hotmail.com,7381270,676195532.0,MADRID,Prestación Autos - Siniestro,No,MADRID NORTE,mapfre_es_5899,Delegacion Madrid Chueca,2026-01-01 10:38:03,10,NaN,P118,DAÃ‘OS PROPIOS LUNAS,TR117,REXCO,EXTRANET DE COLABORADORES,522945906,8109JYL,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T9999,4.0,5899,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.0,2.0,0.0,SIN ASIGNAR,NO APLICA,NO APLICA,No Distinguido,No Centro Servicios,No Taller P@P,NaN,NaN,0.0,NO APLICA
2,Iban,Laperal Toquero,ibanlaperal@gmail.com,27493555,628069459.0,VIZCAYA,Prestación Autos - Siniestro,No,VIZCAYA,mapfre_es_8421,Delegacion Basauri Urb. Lehendakari Agirre,2026-01-01 10:43:39,10,NaN,P131,PAGO ASEGURADO A TERCEROS,TRD29,RSI27,SI24 EXTERNOS III (GSS),521602644,0691HGR,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T0811,2.0,8421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.0,2.0,0.0,SIN ASIGNAR,NO APLICA,NO APLICA,No Distinguido,No Centro Servicios,No Taller P@P,NaN,NaN,0.0,NO APLICA
3,Francisco Javier,Fernandez Piña,javierfp32@hotmail.com,7659060,637195248.0,MALAGA,Prestación Autos - Siniestro,No,MALAGA,mapfre_es_8826,Oficina Marbella,2026-01-01 12:14:33,8,NaN,P131,PAGO ASEGURADO A TERCEROS,TRD4A,R8826,MARBELLA (FONTANILLA),520784007,1933KFC,Reparación de los daños,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,T0811,4.0,8826,NaN,NaN,NaN,520784007,2941268,AUTOS EUROPA,TD,29.0,MALAGA,08 Sur,MARBELLA (ROSIQUE),SUR,FERNANDEZ FERRER,2904.0,PERITACIONES,Perito Honorario,10000045.0,GENERAL MAPFRE AUTOMOVIL,2026.0,2.0,29.0,MALAGA,AUTOS EUROPA,MARBELLA,Distinguido,No Centro Servicios,No Taller P@P,1.0,Chapa,4.0,GENERICO
4,Juan Jose,Olveira Sieira,juanjolveira@gmail.com,4244339,686774814.0,A CORUÑA,Prestación Autos - Siniestro,No,A CORUÑA,mapfre_es_5475,Delegacion Ribeira Rua De Lugo,2026-01-01 12:21:14,10,me repararon la luna media hora después de not...,P118,DAÃ‘OS PROPIOS LUNAS,TR117,REXCO,EXTRANET DE COLABORADORES,523058406,4558NBD,Resolución del siniestro,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,41.0,T9999,5.0,5475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.0,2.0,0.0,SIN ASIGNAR,NO APLICA,NO APLICA,No Distinguido,No Centro Servicios,No Taller P@P,NaN,NaN,0.0,NO APLICA

In [22]:
registros_con_peritos_con_taller = df['ES - Client ID'].count()
print(f"Total Encuestas: {registros_con_peritos_con_taller}")

Total Encuestas: 7426

### 🐍 Nos conectamos al fichero de Expedientes AutoPaP

In [10]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
df_autoPaP = pd.read_csv(r'Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\NPS_Autos\Tablas\03 Auto Puerta a Puerta.txt', encoding="UTF-16", sep="\t")
df_autoPaP.head()

,Expediente,Código Taller,Nombre Taller,Nombre Provincia Taller,Importe Taller
0,516428647,830293,TALLERES AYATS,BARCELONA,"539,18"
1,516646761,4830430,"EL VALLE, TALLERES DE CARROCERÍAS",BIZKAIA,"715,34"
2,516904780,2842281,VSR CAR SERVICE (GRUPO TORREJON),MADRID,"499,2"
3,516911685,2830269,"HABANA MOTOR, S.L.",MADRID,"399,19"
4,516933514,830293,TALLERES AYATS,BARCELONA,"691,04"

### 🐍 Cruzamos la información de medalia + peritos + talleres con AutoPaP

In [11]:
# Cruzamos la información por el campo Expediente para asignar los atributos específicos del AutoPaP
df_autoPaP['Expediente'] = df_autoPaP['Expediente'].astype(str)
df_medalia_peritos_talleres_autopap = pd.merge(df_medalia_peritos_talleres, df_autoPaP, how='left', left_on='ES - General Claim - File Number', right_on='Expediente')
df_medalia_peritos_talleres_autopap.head()

,ES - Client first name,ES - Client last name,Email,ES - Client ID,ES - Phone number,ES - Province,ES - Touchpoint,ES - MAPFRE Santander Record,Export AT Description,ES - Unit ID Text,ES - Unit ID,Fecha de respuesta,ES - NPS including Corredores,ES - Corredores - Verbatim Comment including Corredores,ES - General Claim - Type of claim Code,ES - General Claim - Type of claim Descripction,ES - General Claim - Processor Code,ES - General Claim - Receiving center,ES - General Claim - Center user,ES - General Claim - File Number,ES - Auto - Number Plate,ES - Motivo de valoración - Auto Claim - Corredores,ES - Auto Claim - Satisfaction Atention,ES - Auto Claim - Satisfaction Next Steps,ES - Auto Claim - Satisfaction Proactivity,ES - Auto Claim - Satisfaction Explanations,ES - Auto Claim - Satisfaction Assesment,ES - Auto Claim - Satisfaction Resolution,ES - Auto Claim - Satisfaction Quality,ES - Auto Claim - Satisfaction Repairer,ES - Commerce - Mapfre Entity Code,ES - General Claim - Processor Center,ES - Client Value,oficina,¿Has conseguido contactar con el cliente?,¿El cliente queda conforme?,Indique la propuesta ofrecida al asegurado,Número Expediente,Código Taller_x,Nombre Taller_x,Marca Taller Distnguido,Código Provincia,Nombre Provincia,DGT Taller,Nombre Centro de Peritaciones,Nombre DGT Peritaciones,Apellidos Jefe DGT Peritaciones,Código Perito,Nombre Perito,Nombre Tipo Perito,Código Acuerdo,Nombre Acuerdo,Año Actual,Mes Actual,Código Provincia Taller,Nombre Provincia Taller_x,Nombre Taller_y,Localidad,Marca Taller Distinguido,Marca Taller Centro Servicios (S/N),Marca Taller P@P (S/N),Código Actividad Ppal,Nombre Actividad Ppal,Código Clase Ppal,Nombre Clase Ppal,Expediente,Código Taller_y,Nombre Taller,Nombre Provincia Taller_y,Importe Taller
0,Jose,Adrian Portillo,pepet1963@gmail.com,12294447,637453220.0,VALENCIA,Prestación Autos - Siniestro,No,VALENCIA,mapfre_es_8471,Delegacion Alboraya,2026-01-01 09:16:36,10,Buena atención y rapidez en todos los sentidos,P117,DAÃ‘OS PROPIOS ROBO,TRD7A,R8471,ALBORAYA (HORCHATA),522974731,8885KYF,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T0811,3.0,8471,NaN,NaN,NaN,522974731,4640408,EL XVENIR CARRERA,NO TD,46.0,VALENCIA,05 Este,ALBACETE,CENTRO,CALVO RODRIGUEZ,1251.0,JESUS PABLO,Perito Empleado Mapfre,10000045.0,GENERAL MAPFRE AUTOMOVIL,2026.0,2.0,46.0,VALENCIA,EL XVENIR CARRERA,SILLA,No Distinguido,No Centro Servicios,No Taller P@P,1.0,Chapa,4.0,GENERICO,NaN,NaN,NaN,NaN,NaN
1,Francisco,Estevez Corbacho,francisco-estevez@hotmail.com,7381270,676195532.0,MADRID,Prestación Autos - Siniestro,No,MADRID NORTE,mapfre_es_5899,Delegacion Madrid Chueca,2026-01-01 10:38:03,10,NaN,P118,DAÃ‘OS PROPIOS LUNAS,TR117,REXCO,EXTRANET DE COLABORADORES,522945906,8109JYL,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T9999,4.0,5899,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.0,2.0,0.0,SIN ASIGNAR,NO APLICA,NO APLICA,No Distinguido,No Centro Servicios,No Taller P@P,NaN,NaN,0.0,NO APLICA,NaN,NaN,NaN,NaN,NaN
2,Iban,Laperal Toquero,ibanlaperal@gmail.com,27493555,628069459.0,VIZCAYA,Prestación Autos - Siniestro,No,VIZCAYA,mapfre_es_8421,Delegacion Basauri Urb. Lehendakari Agirre,2026-01-01 10:43:39,10,NaN,P131,PAGO ASEGURADO A TERCEROS,TRD29,RSI27,SI24 EXTERNOS III (GSS),521602644,0691HGR,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T0811,2.0,8421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.0,2.0,0.0,SIN ASIGNAR,NO APLICA,NO APLICA,No Distinguido,No Centro Servicios,No Taller P@P,NaN,NaN,0.0,NO APLICA,NaN,NaN,NaN,NaN,NaN
3,Francisco Javier,Fernandez Piña,javierfp32@hotmail.com,7659060,637195248.0,MALAGA,Prestación Autos - Siniestro,No,MALAGA,mapfre_es_8826,Oficina Marbella,2026-01-01 12:14:33,8,NaN,P131,PAGO ASEGURADO A TERCEROS,TRD4A,R8826,MARBELLA (FONTANILLA),520784007,1933KFC,Reparación de los daños,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,T0811,4.0,8826,NaN,NaN,NaN,520784007,2941268,AUTOS EUROPA,TD,29.0,MALAGA,08 Sur,MARBELLA (ROSIQUE),SUR,FERNANDEZ FERRER,2904.0,PERITACIONES,Perito Honorario,10000045.0,GENERAL MAPFRE AUTOMOVIL,2026.0,2.0,29.0,MALAGA,AUTOS EUROPA,MARBELLA,Distinguido,No Centro Servicios,No Taller P@P,1.0,Chapa,4.0,GENERICO,NaN,NaN,NaN,NaN,NaN
4,Juan Jose,Olveira Sieira,juanjolveira@gmail.com,4244339,686774814.0,A CORUÑA,Prestación Autos - Siniestro,No,A CORUÑA,mapfre_es_5475,Delegacion Ribeira Rua De Lugo,2026-01-01 12:21:14,10,me repararon la luna media hora después de not...,P118,DAÃ‘OS PROPIOS LUNAS,TR117,REXCO,EXTRANET DE COLABORADORES,523058406,4558NBD,Resolución del siniestro,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,41.0,T9999,5.0,5475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.0,2.0,0.0,SIN ASIGNAR,NO APLICA,NO APLICA,No Distinguido,No Centro Servicios,No Taller P@P,NaN,NaN,0.0,NO APLICA,NaN,NaN,NaN,NaN,NaN

### 🐍 Nos conectamos al fichero de Expedientes de DP Lunas

In [12]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
df_lunas = pd.read_csv(r'Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\NPS_Autos\Tablas\04 Lunas.txt', encoding="UTF-16", sep="\t")
df_lunas.head()

C:\Users\RGARCI5\AppData\Local\Temp\ipykernel_16500\1584258788.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_lunas = pd.read_csv(r'Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\NPS_Autos\Tablas\04 Lunas.txt', encoding="UTF-16", sep="\t")

,Expediente,Código Taller,Nombre Taller,Código Grupo Comercial,Nombre Grupo Comercial
0,515676694,2834910,RUSTICAR KITS,0,SIN ASIGNAR
1,515818490,3530341,TALLER EL MOLINO,0,SIN ASIGNAR
2,515918623,3110123,COMERCIAL GAZPI,412,GRUPO GAZPI
3,515929125,4230161,JAICER ELECTROMECÁNICA,0,SIN ASIGNAR
4,515935057,4710118,FUENTEOLID,0,SIN ASIGNAR

### 🐍 Cruzamos la información de medalia + peritos + talleres + AutoPaP con el dataframe df_lunas

In [13]:
# Cruzamos la información por el campo Expediente para asignar los atributos específicos de las reparaciones de Lunas
df_lunas['Expediente'] = df_lunas['Expediente'].astype(str)
df_medalia_peritos_talleres_autopap_lunas = pd.merge(df_medalia_peritos_talleres_autopap,df_lunas,how='left',left_on='ES - General Claim - File Number',
                                                     right_on='Expediente',suffixes=('_medalia', '_lunas'))  # Especifico sufijos para evitar conflictos de mismos nombres de columnas
df_medalia_peritos_talleres_autopap_lunas.head()

,ES - Client first name,ES - Client last name,Email,ES - Client ID,ES - Phone number,ES - Province,ES - Touchpoint,ES - MAPFRE Santander Record,Export AT Description,ES - Unit ID Text,ES - Unit ID,Fecha de respuesta,ES - NPS including Corredores,ES - Corredores - Verbatim Comment including Corredores,ES - General Claim - Type of claim Code,ES - General Claim - Type of claim Descripction,ES - General Claim - Processor Code,ES - General Claim - Receiving center,ES - General Claim - Center user,ES - General Claim - File Number,ES - Auto - Number Plate,ES - Motivo de valoración - Auto Claim - Corredores,ES - Auto Claim - Satisfaction Atention,ES - Auto Claim - Satisfaction Next Steps,ES - Auto Claim - Satisfaction Proactivity,ES - Auto Claim - Satisfaction Explanations,ES - Auto Claim - Satisfaction Assesment,ES - Auto Claim - Satisfaction Resolution,ES - Auto Claim - Satisfaction Quality,ES - Auto Claim - Satisfaction Repairer,ES - Commerce - Mapfre Entity Code,ES - General Claim - Processor Center,ES - Client Value,oficina,¿Has conseguido contactar con el cliente?,¿El cliente queda conforme?,Indique la propuesta ofrecida al asegurado,Número Expediente,Código Taller_x,Nombre Taller_x,Marca Taller Distnguido,Código Provincia,Nombre Provincia,DGT Taller,Nombre Centro de Peritaciones,Nombre DGT Peritaciones,Apellidos Jefe DGT Peritaciones,Código Perito,Nombre Perito,Nombre Tipo Perito,Código Acuerdo,Nombre Acuerdo,Año Actual,Mes Actual,Código Provincia Taller,Nombre Provincia Taller_x,Nombre Taller_y,Localidad,Marca Taller Distinguido,Marca Taller Centro Servicios (S/N),Marca Taller P@P (S/N),Código Actividad Ppal,Nombre Actividad Ppal,Código Clase Ppal,Nombre Clase Ppal,Expediente_medalia,Código Taller_y,Nombre Taller_medalia,Nombre Provincia Taller_y,Importe Taller,Expediente_lunas,Código Taller,Nombre Taller_lunas,Código Grupo Comercial,Nombre Grupo Comercial
0,Jose,Adrian Portillo,pepet1963@gmail.com,12294447,637453220.0,VALENCIA,Prestación Autos - Siniestro,No,VALENCIA,mapfre_es_8471,Delegacion Alboraya,2026-01-01 09:16:36,10,Buena atención y rapidez en todos los sentidos,P117,DAÃ‘OS PROPIOS ROBO,TRD7A,R8471,ALBORAYA (HORCHATA),522974731,8885KYF,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T0811,3.0,8471,NaN,NaN,NaN,522974731,4640408,EL XVENIR CARRERA,NO TD,46.0,VALENCIA,05 Este,ALBACETE,CENTRO,CALVO RODRIGUEZ,1251.0,JESUS PABLO,Perito Empleado Mapfre,10000045.0,GENERAL MAPFRE AUTOMOVIL,2026.0,2.0,46.0,VALENCIA,EL XVENIR CARRERA,SILLA,No Distinguido,No Centro Servicios,No Taller P@P,1.0,Chapa,4.0,GENERICO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Francisco,Estevez Corbacho,francisco-estevez@hotmail.com,7381270,676195532.0,MADRID,Prestación Autos - Siniestro,No,MADRID NORTE,mapfre_es_5899,Delegacion Madrid Chueca,2026-01-01 10:38:03,10,NaN,P118,DAÃ‘OS PROPIOS LUNAS,TR117,REXCO,EXTRANET DE COLABORADORES,522945906,8109JYL,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T9999,4.0,5899,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.0,2.0,0.0,SIN ASIGNAR,NO APLICA,NO APLICA,No Distinguido,No Centro Servicios,No Taller P@P,NaN,NaN,0.0,NO APLICA,NaN,NaN,NaN,NaN,NaN,522945906,2841426,CARGLASS ( CENTRO LOGISTICO ),1.0,CARGLASS
2,Iban,Laperal Toquero,ibanlaperal@gmail.com,27493555,628069459.0,VIZCAYA,Prestación Autos - Siniestro,No,VIZCAYA,mapfre_es_8421,Delegacion Basauri Urb. Lehendakari Agirre,2026-01-01 10:43:39,10,NaN,P131,PAGO ASEGURADO A TERCEROS,TRD29,RSI27,SI24 EXTERNOS III (GSS),521602644,0691HGR,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T0811,2.0,8421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.0,2.0,0.0,SIN ASIGNAR,NO APLICA,NO APLICA,No Distinguido,No Centro Servicios,No Taller P@P,NaN,NaN,0.0,NO APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Francisco Javier,Fernandez Piña,javierfp32@hotmail.com,7659060,637195248.0,MALAGA,Prestación Autos - Siniestro,No,MALAGA,mapfre_es_8826,Oficina Marbella,2026-01-01 12:14:33,8,NaN,P131,PAGO ASEGURADO A TERCEROS,TRD4A,R8826,MARBELLA (FONTANILLA),520784007,1933KFC,Reparación de los daños,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,T0811,4.0,8826,NaN,NaN,NaN,520784007,2941268,AUTOS EUROPA,TD,29.0,MALAGA,08 Sur,MARBELLA (ROSIQUE),SUR,FERNANDEZ FERRER,2904.0,PERITACIONES,Perito Honorario,10000045.0,GENERAL MAPFRE AUTOMOVIL,2026.0,2.0,29.0,MALAGA,AUTOS EUROPA,MARBELLA,Distinguido,No Centro Servicios,No Taller P@P,1.0,Chapa,4.0,GENERICO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Juan Jose,Olveira Sieira,juanjolveira@gmail.com,4244339,686774814.0,A CORUÑA,Prestación Autos - Siniestro,No,A CORUÑA,mapfre_es_5475,Delegacion Ribeira Rua De Lugo,2026-01-01 12:21:14,10,me repararon la luna media hora después de not...,P118,DAÃ‘OS PROPIOS LUNAS,TR117,REXCO,EXTRANET DE COLABORADORES,523058406,4558NBD,Resolución del siniestro,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,41.0,T9999,5.0,5475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.0,2.0,0.0,SIN ASIGNAR,NO APLICA,NO APLICA,No Distinguido,No Centro Servicios,No Taller P@P,NaN,NaN,0.0,NO APLICA,NaN,NaN,NaN,NaN,NaN,523058406,2841426,CARGLASS ( CENTRO LOGISTICO ),1.0,CARGLASS

### 🐍 Nos conectamos al fichero excel Centros de Servicio.xlsx

In [14]:
df_cs = pd.read_excel(r'Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\NPS_Autos\Tablas\Centros de Servicio.xlsx')
df_cs.head()

  CENTRO SERVICIO  EXPEDIENTE TRAMES
0       LAS ROZAS          512945207
1        VALENCIA          519664560
2        ALBACETE          519322007
3       LAS ROZAS          514468147
4        ALCORCÓN          515740663

In [15]:
tipo_dato_cs = df_cs["EXPEDIENTE TRAMES"].dtype
print(f"El tipo de dato de la columna 'EXPEDIENTE TRAMES' es: {tipo_dato}")

El tipo de dato de la columna 'EXPEDIENTE TRAMES' es: object

### 🐍 Cruzamos la información de medalia + peritos + talleres + AutoPaP + lunas con el dataframe df_cs

In [16]:
df_medalia_peritos_talleres_autopap_lunas['ES - General Claim - File Number'] = df_medalia_peritos_talleres_autopap_lunas['ES - General Claim - File Number'].astype(str)
df_cs['EXPEDIENTE TRAMES'] = df_cs['EXPEDIENTE TRAMES'].astype(str)
df_cruce = pd.merge(
    df_medalia_peritos_talleres_autopap_lunas,df_cs,how='left',left_on='ES - General Claim - File Number',right_on='EXPEDIENTE TRAMES')
df_cruce.head()

,ES - Client first name,ES - Client last name,Email,ES - Client ID,ES - Phone number,ES - Province,ES - Touchpoint,ES - MAPFRE Santander Record,Export AT Description,ES - Unit ID Text,ES - Unit ID,Fecha de respuesta,ES - NPS including Corredores,ES - Corredores - Verbatim Comment including Corredores,ES - General Claim - Type of claim Code,ES - General Claim - Type of claim Descripction,ES - General Claim - Processor Code,ES - General Claim - Receiving center,ES - General Claim - Center user,ES - General Claim - File Number,ES - Auto - Number Plate,ES - Motivo de valoración - Auto Claim - Corredores,ES - Auto Claim - Satisfaction Atention,ES - Auto Claim - Satisfaction Next Steps,ES - Auto Claim - Satisfaction Proactivity,ES - Auto Claim - Satisfaction Explanations,ES - Auto Claim - Satisfaction Assesment,ES - Auto Claim - Satisfaction Resolution,ES - Auto Claim - Satisfaction Quality,ES - Auto Claim - Satisfaction Repairer,ES - Commerce - Mapfre Entity Code,ES - General Claim - Processor Center,ES - Client Value,oficina,¿Has conseguido contactar con el cliente?,¿El cliente queda conforme?,Indique la propuesta ofrecida al asegurado,Número Expediente,Código Taller_x,Nombre Taller_x,Marca Taller Distnguido,Código Provincia,Nombre Provincia,DGT Taller,Nombre Centro de Peritaciones,Nombre DGT Peritaciones,Apellidos Jefe DGT Peritaciones,Código Perito,Nombre Perito,Nombre Tipo Perito,Código Acuerdo,Nombre Acuerdo,Año Actual,Mes Actual,Código Provincia Taller,Nombre Provincia Taller_x,Nombre Taller_y,Localidad,Marca Taller Distinguido,Marca Taller Centro Servicios (S/N),Marca Taller P@P (S/N),Código Actividad Ppal,Nombre Actividad Ppal,Código Clase Ppal,Nombre Clase Ppal,Expediente_medalia,Código Taller_y,Nombre Taller_medalia,Nombre Provincia Taller_y,Importe Taller,Expediente_lunas,Código Taller,Nombre Taller_lunas,Código Grupo Comercial,Nombre Grupo Comercial,CENTRO SERVICIO,EXPEDIENTE TRAMES
0,Jose,Adrian Portillo,pepet1963@gmail.com,12294447,637453220.0,VALENCIA,Prestación Autos - Siniestro,No,VALENCIA,mapfre_es_8471,Delegacion Alboraya,2026-01-01 09:16:36,10,Buena atención y rapidez en todos los sentidos,P117,DAÃ‘OS PROPIOS ROBO,TRD7A,R8471,ALBORAYA (HORCHATA),522974731,8885KYF,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T0811,3.0,8471,NaN,NaN,NaN,522974731,4640408,EL XVENIR CARRERA,NO TD,46.0,VALENCIA,05 Este,ALBACETE,CENTRO,CALVO RODRIGUEZ,1251.0,JESUS PABLO,Perito Empleado Mapfre,10000045.0,GENERAL MAPFRE AUTOMOVIL,2026.0,2.0,46.0,VALENCIA,EL XVENIR CARRERA,SILLA,No Distinguido,No Centro Servicios,No Taller P@P,1.0,Chapa,4.0,GENERICO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Francisco,Estevez Corbacho,francisco-estevez@hotmail.com,7381270,676195532.0,MADRID,Prestación Autos - Siniestro,No,MADRID NORTE,mapfre_es_5899,Delegacion Madrid Chueca,2026-01-01 10:38:03,10,NaN,P118,DAÃ‘OS PROPIOS LUNAS,TR117,REXCO,EXTRANET DE COLABORADORES,522945906,8109JYL,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T9999,4.0,5899,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.0,2.0,0.0,SIN ASIGNAR,NO APLICA,NO APLICA,No Distinguido,No Centro Servicios,No Taller P@P,NaN,NaN,0.0,NO APLICA,NaN,NaN,NaN,NaN,NaN,522945906,2841426,CARGLASS ( CENTRO LOGISTICO ),1.0,CARGLASS,NaN,NaN
2,Iban,Laperal Toquero,ibanlaperal@gmail.com,27493555,628069459.0,VIZCAYA,Prestación Autos - Siniestro,No,VIZCAYA,mapfre_es_8421,Delegacion Basauri Urb. Lehendakari Agirre,2026-01-01 10:43:39,10,NaN,P131,PAGO ASEGURADO A TERCEROS,TRD29,RSI27,SI24 EXTERNOS III (GSS),521602644,0691HGR,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T0811,2.0,8421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.0,2.0,0.0,SIN ASIGNAR,NO APLICA,NO APLICA,No Distinguido,No Centro Servicios,No Taller P@P,NaN,NaN,0.0,NO APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Francisco Javier,Fernandez Piña,javierfp32@hotmail.com,7659060,637195248.0,MALAGA,Prestación Autos - Siniestro,No,MALAGA,mapfre_es_8826,Oficina Marbella,2026-01-01 12:14:33,8,NaN,P131,PAGO ASEGURADO A TERCEROS,TRD4A,R8826,MARBELLA (FONTANILLA),520784007,1933KFC,Reparación de los daños,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,T0811,4.0,8826,NaN,NaN,NaN,520784007,2941268,AUTOS EUROPA,TD,29.0,MALAGA,08 Sur,MARBELLA (ROSIQUE),SUR,FERNANDEZ FERRER,2904.0,PERITACIONES,Perito Honorario,10000045.0,GENERAL MAPFRE AUTOMOVIL,2026.0,2.0,29.0,MALAGA,AUTOS EUROPA,MARBELLA,Distinguido,No Centro Servicios,No Taller P@P,1.0,Chapa,4.0,GENERICO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Juan Jose,Olveira Sieira,juanjolveira@gmail.com,4244339,686774814.0,A CORUÑA,Prestación Autos - Siniestro,No,A CORUÑA,mapfre_es_5475,Delegacion Ribeira Rua De Lugo,2026-01-01 12:21:14,10,me repararon la luna media hora después de not...,P118,DAÃ‘OS PROPIOS LUNAS,TR117,REXCO,EXTRANET DE COLABORADORES,523058406,4558NBD,Resolución del siniestro,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,41.0,T9999,5.0,5475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.0,2.0,0.0,SIN ASIGNAR,NO APLICA,NO APLICA,No Distinguido,No Centro Servicios,No Taller P@P,NaN,NaN,0.0,NO APLICA,NaN,NaN,NaN,NaN,NaN,523058406,2841426,CARGLASS ( CENTRO LOGISTICO ),1.0,CARGLASS,NaN,NaN

### 🐍 Nos conectamos al fichero de Tramitadores

In [17]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
df_tramitadores = pd.read_csv(r'Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\NPS_Autos\Tablas\05 Tramitadores.txt', encoding="UTF-16", sep="\t")
df_tramitadores.head()

,Fecha Actual,Código Jefe Equipo Actual,Nombre Jefe Equipo Actual,Código Tramitador Actual,Nombre Tramitador Actual,Código Centro Tramitador Actual
0,01/01/2026 0:00,TRS4C,REINO PREGO BEATRIZ,TRS55,BLANCO SAAVEDRA CARLOS JOSE,T8515
1,01/01/2026 0:00,TRZ07,BENAVENT TORRES JOSE VICENTE,TRZ13,PORRAS PEREZ ALICIA,T7015
2,01/01/2026 0:00,TRD79,LLADRO ORTI MIQUEL,TRD94,BARREDA SANTA CRUZ BEGOÑA,T0811
3,01/01/2026 0:00,TRZ04,CRESPO LOZANO SONIA,TRZ2C,BRITO MESA M DEL PINO,T7015
4,01/01/2026 0:00,TRD05,ALONSO LAIN JESUS,TRD45,CASTELLON BOSQUET BEGOÑA,T0811

In [18]:
df_cruce_tramita = pd.merge(df_cruce,df_tramitadores,how='left',left_on='ES - General Claim - Processor Code',right_on='Código Tramitador Actual')
df_cruce_tramita.head()

,ES - Client first name,ES - Client last name,Email,ES - Client ID,ES - Phone number,ES - Province,ES - Touchpoint,ES - MAPFRE Santander Record,Export AT Description,ES - Unit ID Text,ES - Unit ID,Fecha de respuesta,ES - NPS including Corredores,ES - Corredores - Verbatim Comment including Corredores,ES - General Claim - Type of claim Code,ES - General Claim - Type of claim Descripction,ES - General Claim - Processor Code,ES - General Claim - Receiving center,ES - General Claim - Center user,ES - General Claim - File Number,ES - Auto - Number Plate,ES - Motivo de valoración - Auto Claim - Corredores,ES - Auto Claim - Satisfaction Atention,ES - Auto Claim - Satisfaction Next Steps,ES - Auto Claim - Satisfaction Proactivity,ES - Auto Claim - Satisfaction Explanations,ES - Auto Claim - Satisfaction Assesment,ES - Auto Claim - Satisfaction Resolution,ES - Auto Claim - Satisfaction Quality,ES - Auto Claim - Satisfaction Repairer,ES - Commerce - Mapfre Entity Code,ES - General Claim - Processor Center,ES - Client Value,oficina,¿Has conseguido contactar con el cliente?,¿El cliente queda conforme?,Indique la propuesta ofrecida al asegurado,Número Expediente,Código Taller_x,Nombre Taller_x,Marca Taller Distnguido,Código Provincia,Nombre Provincia,DGT Taller,Nombre Centro de Peritaciones,Nombre DGT Peritaciones,Apellidos Jefe DGT Peritaciones,Código Perito,Nombre Perito,Nombre Tipo Perito,Código Acuerdo,Nombre Acuerdo,Año Actual,Mes Actual,Código Provincia Taller,Nombre Provincia Taller_x,Nombre Taller_y,Localidad,Marca Taller Distinguido,Marca Taller Centro Servicios (S/N),Marca Taller P@P (S/N),Código Actividad Ppal,Nombre Actividad Ppal,Código Clase Ppal,Nombre Clase Ppal,Expediente_medalia,Código Taller_y,Nombre Taller_medalia,Nombre Provincia Taller_y,Importe Taller,Expediente_lunas,Código Taller,Nombre Taller_lunas,Código Grupo Comercial,Nombre Grupo Comercial,CENTRO SERVICIO,EXPEDIENTE TRAMES,Fecha Actual,Código Jefe Equipo Actual,Nombre Jefe Equipo Actual,Código Tramitador Actual,Nombre Tramitador Actual,Código Centro Tramitador Actual
0,Jose,Adrian Portillo,pepet1963@gmail.com,12294447,637453220.0,VALENCIA,Prestación Autos - Siniestro,No,VALENCIA,mapfre_es_8471,Delegacion Alboraya,2026-01-01 09:16:36,10,Buena atención y rapidez en todos los sentidos,P117,DAÃ‘OS PROPIOS ROBO,TRD7A,R8471,ALBORAYA (HORCHATA),522974731,8885KYF,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T0811,3.0,8471,NaN,NaN,NaN,522974731,4640408,EL XVENIR CARRERA,NO TD,46.0,VALENCIA,05 Este,ALBACETE,CENTRO,CALVO RODRIGUEZ,1251.0,JESUS PABLO,Perito Empleado Mapfre,10000045.0,GENERAL MAPFRE AUTOMOVIL,2026.0,2.0,46.0,VALENCIA,EL XVENIR CARRERA,SILLA,No Distinguido,No Centro Servicios,No Taller P@P,1.0,Chapa,4.0,GENERICO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/01/2026 0:00,TRD79,LLADRO ORTI MIQUEL,TRD7A,CID ACED JAVIER,T0811
1,Francisco,Estevez Corbacho,francisco-estevez@hotmail.com,7381270,676195532.0,MADRID,Prestación Autos - Siniestro,No,MADRID NORTE,mapfre_es_5899,Delegacion Madrid Chueca,2026-01-01 10:38:03,10,NaN,P118,DAÃ‘OS PROPIOS LUNAS,TR117,REXCO,EXTRANET DE COLABORADORES,522945906,8109JYL,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T9999,4.0,5899,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.0,2.0,0.0,SIN ASIGNAR,NO APLICA,NO APLICA,No Distinguido,No Centro Servicios,No Taller P@P,NaN,NaN,0.0,NO APLICA,NaN,NaN,NaN,NaN,NaN,522945906,2841426,CARGLASS ( CENTRO LOGISTICO ),1.0,CARGLASS,NaN,NaN,01/01/2026 0:00,TR187,SANTAMARIA GARCIA MARTA,TR117,HERNANDEZ BLAZQUEZ EVA MARIA,T9999
2,Iban,Laperal Toquero,ibanlaperal@gmail.com,27493555,628069459.0,VIZCAYA,Prestación Autos - Siniestro,No,VIZCAYA,mapfre_es_8421,Delegacion Basauri Urb. Lehendakari Agirre,2026-01-01 10:43:39,10,NaN,P131,PAGO ASEGURADO A TERCEROS,TRD29,RSI27,SI24 EXTERNOS III (GSS),521602644,0691HGR,Resolución del siniestro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,T0811,2.0,8421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.0,2.0,0.0,SIN ASIGNAR,NO APLICA,NO APLICA,No Distinguido,No Centro Servicios,No Taller P@P,NaN,NaN,0.0,NO APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/01/2026 0:00,TRD28,ROBLES SANCHEZ LAURA,TRD29,HERRAN CORBACHO DIANA,T0811
3,Francisco Javier,Fernandez Piña,javierfp32@hotmail.com,7659060,637195248.0,MALAGA,Prestación Autos - Siniestro,No,MALAGA,mapfre_es_8826,Oficina Marbella,2026-01-01 12:14:33,8,NaN,P131,PAGO ASEGURADO A TERCEROS,TRD4A,R8826,MARBELLA (FONTANILLA),520784007,1933KFC,Reparación de los daños,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,T0811,4.0,8826,NaN,NaN,NaN,520784007,2941268,AUTOS EUROPA,TD,29.0,MALAGA,08 Sur,MARBELLA (ROSIQUE),SUR,FERNANDEZ FERRER,2904.0,PERITACIONES,Perito Honorario,10000045.0,GENERAL MAPFRE AUTOMOVIL,2026.0,2.0,29.0,MALAGA,AUTOS EUROPA,MARBELLA,Distinguido,No Centro Servicios,No Taller P@P,1.0,Chapa,4.0,GENERICO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/01/2026 0:00,TRD50,GIJON NIETO CARLOS,TRD4A,COMAS LLORET SILVIA,T0811
4,Juan Jose,Olveira Sieira,juanjolveira@gmail.com,4244339,686774814.0,A CORUÑA,Prestación Autos - Siniestro,No,A CORUÑA,mapfre_es_5475,Delegacion Ribeira Rua De Lugo,2026-01-01 12:21:14,10,me repararon la luna media hora después de not...,P118,DAÃ‘OS PROPIOS LUNAS,TR117,REXCO,EXTRANET DE COLABORADORES,523058406,4558NBD,Resolución del siniestro,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,41.0,T9999,5.0,5475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.0,2.0,0.0,SIN ASIGNAR,NO APLICA,NO APLICA,No Distinguido,No Centro Servicios,No Taller P@P,NaN,NaN,0.0,NO APLICA,NaN,NaN,NaN,NaN,NaN,523058406,2841426,CARGLASS ( CENTRO LOGISTICO ),1.0,CARGLASS,NaN,NaN,01/01/2026 0:00,TR187,SANTAMARIA GARCIA MARTA,TR117,HERNANDEZ BLAZQUEZ EVA MARIA,T9999

### 🐍 Exportamos a Excel el fichero del NPS de Siniestros Autos

In [21]:
total_registros = df_cruce_tramita['ES - Client ID'].count()
print(f"Total Encuestas: {total_registros}")

Total Encuestas: 7426

In [20]:
df_cruce_tramita.to_excel(r'Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\NPS_Autos\nps_autos.xlsx', index=False)
print("■"*80)
print("  El fichero del NPS de Siniestros Automóviles se ha exportado correctamente")
print("■"*80)

■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  El fichero del NPS de Siniestros Automóviles se ha exportado correctamente
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■