### 🐍 Nos conectamos con el fichero de Medallia y únicamente nos quedamos con los campos que nos interesan

In [27]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
df = pd.read_excel(r'Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\EXPORT PRESTACIONES.xlsx')
df['oficina'] = df['ES - Unit ID Text'].str.replace('mapfre_es_', '', regex=False)
df = df[df['ES - Touchpoint'] == 'Prestación Hogar']
columnas = [
"ES - Client first name",
"ES - Client last name",
"Email",	
"ES - Client ID",
"ES - Phone number",
"ES - Province",
"ES - Touchpoint",
"ES - MAPFRE Santander Record",
"Export AT Description",
"ES - Unit ID Text",
"ES - Unit ID",
"ES - Agent",
"Fecha de respuesta",
"ES - NPS including Corredores",
"ES - Corredores - Verbatim Comment including Corredores",
"ES - Policy number",
"ES - Contact Intrest including Corredores",
"ES - General Claim - Type of claim Descripction",
"ES - General Claim - File Number",
"ES - General Claim - Processor Name",
"ES - Home - Number repair Services",
"ES - Home - Activity Repair Code",
"ES - Home - Risk Address Town",
"ES - Home - Risk Address Province",
"ES - Home - Risk Address Postal Code",
"ES- Motivo de valoración - Hogar - Corredores",
"ES - Centro Tramitador Hogar, Multirriesgo",
"ES - Home - Satisfaction Repairers Service including Corredores",
"ES - Home -  Satisfaction Claim Management including Corredores",
"ES - Home - Satisfaction Information including Corredores",
"ES - Home - Satisfaction Proactivity including Corredores",
"ES - Home - Satisfaction Communication including Corredores",
"ES - Home - Satisfaction Repair Quality including Corredores",
"¿Has conseguido contactar con el cliente?",
"¿El cliente queda conforme?",
"Observaciones",
"Indique el motivo de insatisfacción detectado en el asegurado:",
"Indique la propuesta ofrecida al asegurado",
"Si ha seleccionado 'Otros', por favor especifique cuál",
"oficina"
]
df=df[columnas]
df.head()

,ES - Client first name,ES - Client last name,Email,ES - Client ID,ES - Phone number,ES - Province,ES - Touchpoint,ES - MAPFRE Santander Record,Export AT Description,ES - Unit ID Text,ES - Unit ID,ES - Agent,Fecha de respuesta,ES - NPS including Corredores,ES - Corredores - Verbatim Comment including Corredores,ES - Policy number,ES - Contact Intrest including Corredores,ES - General Claim - Type of claim Descripction,ES - General Claim - File Number,ES - General Claim - Processor Name,ES - Home - Number repair Services,ES - Home - Activity Repair Code,ES - Home - Risk Address Town,ES - Home - Risk Address Province,ES - Home - Risk Address Postal Code,ES- Motivo de valoración - Hogar - Corredores,"ES - Centro Tramitador Hogar, Multirriesgo",ES - Home - Satisfaction Repairers Service including Corredores,ES - Home - Satisfaction Claim Management including Corredores,ES - Home - Satisfaction Information including Corredores,ES - Home - Satisfaction Proactivity including Corredores,ES - Home - Satisfaction Communication including Corredores,ES - Home - Satisfaction Repair Quality including Corredores,¿Has conseguido contactar con el cliente?,¿El cliente queda conforme?,Observaciones,Indique el motivo de insatisfacción detectado en el asegurado:,Indique la propuesta ofrecida al asegurado,"Si ha seleccionado 'Otros', por favor especifique cuál",oficina
4,Leandro,Casamitjana Rossello,lpm828@hotmail.com,31214918,608724208.0,BARCELONA,Prestación Hogar,No,CATALUÑA NORTE,mapfre_es_5529,Delegacion Artes,5283864,2026-01-01 09:18:43,0,Hoy a 1 de enero de 2026 ningun operació ha ve...,732200197580,Sí,BRICOLAJE EN EL HOGAR,V55660291,ANA BELEN CUNTIN PEREZ,1.0,01,Navas,BARCELONA,8670.0,Resolución del siniestro,CMP Reparables,NaN,NaN,NaN,NaN,NaN,NaN,Otro motivo,Sí,CORRESPOPNDE V55662061,Otros,NaN,NaN,5529
5,Graciela,Chetrit Russi,gracielaches@yahoo.es,11515548,629721064.0,GIRONA,Prestación Hogar,No,CATALUÑA NORTE,mapfre_es_1773,Delegacion Girona Urb. Xavier Cugat,170776,2026-01-01 09:22:02,10,"La atencion recibida , y la buena resolucion .",730880036859,NaN,ROBO,V56213511,OLGA DE LA MORENA BRIONES,1.0,16,Girona,GIRONA,17003.0,Resolución del siniestro,CMP Reparables,9.0,9.0,9.0,9.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,1773
6,Jose Antonio,Merino Martin,jmerinom@telefonica.net,445728,626363401.0,MADRID,Prestación Hogar,No,MADRID SUR,mapfre_es_6713,Delegacion Coslada Argentina,5270757,2026-01-01 09:23:53,10,Personal muy profesional y resolutivo.,732200074430,NaN,BRICOLAJE EN EL HOGAR,V56017561,PIEDAD ASENSIO,1.0,02,San Fernando De Henares,MADRID,28830.0,Intervención de los reparadores,CMP Reparables,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sí,NaN,NaN,NaN,NaN,6713
8,Maria Jesus,De Lorenzo Garcia,mj_lorengar@yahoo.es,19715949,627036490.0,MADRID,Prestación Hogar,No,MADRID SUR,mapfre_es_6183,Delegacion Madrid Paseo Pontones,5281192,2026-01-01 09:48:25,9,NaN,732300146131,NaN,AGUA,V52830341,NURIA RUIZ BLANCO,3.0,01||03||04,Madrid,MADRID,28005.0,Resolución del siniestro,CMP Reparables,9.0,9.0,NaN,9.0,9.0,9.0,NaN,Desconocido (no contacto),NaN,NaN,NaN,NaN,6183
9,Lourdes,Palacios Martin,lourpalacios@gmail.com,35310782,646516388.0,VIZCAYA,Prestación Hogar,No,SALAMANCA,mapfre_es_5754,Delegacion Ciudad Rodrigo,370934,2026-01-01 09:50:19,10,NaN,732300326228,NaN,CRISTALES / ROTURAS,V56174001,RAQUEL MORENO ALONSO(GSS-ROTURAS),1.0,VT,Bilbao,VIZCAYA,48004.0,Cobro de indemnización,CMP Reparables,10.0,10.0,10.0,10.0,10.0,10.0,NaN,Sí,NaN,NaN,NaN,NaN,5754

In [29]:
duplicados = df["ES - General Claim - File Number"].value_counts()
duplicados[duplicados > 1]

ES - General Claim - File Number
V55619201    2
V59942941    2
Name: count, dtype: int64

In [2]:
encuestas = df['ES - Client ID'].count()
print(f"Total Encuestas: {encuestas}")

Total Encuestas: 29915

In [3]:
tipo_dato = df["ES - General Claim - File Number"].dtype
print(f"El tipo de dato de la columna 'ES - General Claim - File Number' es: {tipo_dato}")

El tipo de dato de la columna 'ES - General Claim - File Number' es: str

### 🐍 Nos conectamos con el fichero de Peritaciones

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
df_peritos = pd.read_excel(r'Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\NPS_Hogar\Tablas\Peritos.xlsx')
df_peritos.head()

,Código DGT,Número Expediente Operacional,Código Profesional,Nombre Profesional,Nº de profesionales distintos por expte
0,4,B00091902,07P63,JOSE LUIS ASIN BERNAL,1
1,1,B00097421,0709Y,MERCEDES MARHUENDA BONILLO,1
2,2,B00127131,070GV,FRANCESC SERRANO SUAREZ,1
3,4,B00129374,071AB,ROBERTO DE LA PRIETA SABORIDO,1
4,6,B00133472,070A3,JUAN GUTIERREZ SAN EMETERIO,1

### 🐍 Cruzamos la información de Medallia con la de Peritaciones

In [5]:
# Los campos de expediente los cambio a tipo string para poder cruzar la información
df['ES - General Claim - File Number'] = df['ES - General Claim - File Number'].astype(str)
df_peritos['Número Expediente Operacional'] = df_peritos['Número Expediente Operacional'].astype(str)
df_medalia_peritos = pd.merge(df, df_peritos, how='left', left_on='ES - General Claim - File Number', right_on='Número Expediente Operacional')
df_medalia_peritos.head()

,ES - Client first name,ES - Client last name,Email,ES - Client ID,ES - Phone number,ES - Province,ES - Touchpoint,ES - MAPFRE Santander Record,Export AT Description,ES - Unit ID Text,ES - Unit ID,ES - Agent,Fecha de respuesta,ES - NPS including Corredores,ES - Corredores - Verbatim Comment including Corredores,ES - Policy number,ES - Contact Intrest including Corredores,ES - General Claim - Type of claim Descripction,ES - General Claim - File Number,ES - General Claim - Processor Name,ES - Home - Number repair Services,ES - Home - Activity Repair Code,ES - Home - Risk Address Town,ES - Home - Risk Address Province,ES - Home - Risk Address Postal Code,ES- Motivo de valoración - Hogar - Corredores,"ES - Centro Tramitador Hogar, Multirriesgo",ES - Home - Satisfaction Repairers Service including Corredores,ES - Home - Satisfaction Claim Management including Corredores,ES - Home - Satisfaction Information including Corredores,ES - Home - Satisfaction Proactivity including Corredores,ES - Home - Satisfaction Communication including Corredores,ES - Home - Satisfaction Repair Quality including Corredores,¿Has conseguido contactar con el cliente?,¿El cliente queda conforme?,Observaciones,Indique el motivo de insatisfacción detectado en el asegurado:,Indique la propuesta ofrecida al asegurado,"Si ha seleccionado 'Otros', por favor especifique cuál",oficina,Código DGT,Número Expediente Operacional,Código Profesional,Nombre Profesional,Nº de profesionales distintos por expte
0,Leandro,Casamitjana Rossello,lpm828@hotmail.com,31214918,608724208.0,BARCELONA,Prestación Hogar,No,CATALUÑA NORTE,mapfre_es_5529,Delegacion Artes,5283864,2026-01-01 09:18:43,0,Hoy a 1 de enero de 2026 ningun operació ha ve...,732200197580,Sí,BRICOLAJE EN EL HOGAR,V55660291,ANA BELEN CUNTIN PEREZ,1.0,01,Navas,BARCELONA,8670.0,Resolución del siniestro,CMP Reparables,NaN,NaN,NaN,NaN,NaN,NaN,Otro motivo,Sí,CORRESPOPNDE V55662061,Otros,NaN,NaN,5529,NaN,NaN,NaN,NaN,NaN
1,Graciela,Chetrit Russi,gracielaches@yahoo.es,11515548,629721064.0,GIRONA,Prestación Hogar,No,CATALUÑA NORTE,mapfre_es_1773,Delegacion Girona Urb. Xavier Cugat,170776,2026-01-01 09:22:02,10,"La atencion recibida , y la buena resolucion .",730880036859,NaN,ROBO,V56213511,OLGA DE LA MORENA BRIONES,1.0,16,Girona,GIRONA,17003.0,Resolución del siniestro,CMP Reparables,9.0,9.0,9.0,9.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,1773,NaN,NaN,NaN,NaN,NaN
2,Jose Antonio,Merino Martin,jmerinom@telefonica.net,445728,626363401.0,MADRID,Prestación Hogar,No,MADRID SUR,mapfre_es_6713,Delegacion Coslada Argentina,5270757,2026-01-01 09:23:53,10,Personal muy profesional y resolutivo.,732200074430,NaN,BRICOLAJE EN EL HOGAR,V56017561,PIEDAD ASENSIO,1.0,02,San Fernando De Henares,MADRID,28830.0,Intervención de los reparadores,CMP Reparables,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sí,NaN,NaN,NaN,NaN,6713,NaN,NaN,NaN,NaN,NaN
3,Maria Jesus,De Lorenzo Garcia,mj_lorengar@yahoo.es,19715949,627036490.0,MADRID,Prestación Hogar,No,MADRID SUR,mapfre_es_6183,Delegacion Madrid Paseo Pontones,5281192,2026-01-01 09:48:25,9,NaN,732300146131,NaN,AGUA,V52830341,NURIA RUIZ BLANCO,3.0,01||03||04,Madrid,MADRID,28005.0,Resolución del siniestro,CMP Reparables,9.0,9.0,NaN,9.0,9.0,9.0,NaN,Desconocido (no contacto),NaN,NaN,NaN,NaN,6183,NaN,NaN,NaN,NaN,NaN
4,Lourdes,Palacios Martin,lourpalacios@gmail.com,35310782,646516388.0,VIZCAYA,Prestación Hogar,No,SALAMANCA,mapfre_es_5754,Delegacion Ciudad Rodrigo,370934,2026-01-01 09:50:19,10,NaN,732300326228,NaN,CRISTALES / ROTURAS,V56174001,RAQUEL MORENO ALONSO(GSS-ROTURAS),1.0,VT,Bilbao,VIZCAYA,48004.0,Cobro de indemnización,CMP Reparables,10.0,10.0,10.0,10.0,10.0,10.0,NaN,Sí,NaN,NaN,NaN,NaN,5754,NaN,NaN,NaN,NaN,NaN

In [6]:
registros_con_peritos = df['ES - Client ID'].count()
print(f"Total Encuestas: {registros_con_peritos}")

Total Encuestas: 29915

### 🐍 Me conecto al fichero de Servicios.txt al que he agregado manualmente los registros del último mes que me pasan desde proveedores

In [7]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
df_servicios = pd.read_csv(r'Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\NPS_Hogar\Tablas\Servicios.txt', encoding="MacRoman", sep="\t")
df_servicios.head()

  N. Expediente CÛd. profesional asignado    Nombre del proveedor asignado
0     V54175711                     9505U        PEDRO MANUEL SOLER PADRON
1     V59166961                     9506X                 AVILA & GO, S.L.
2     V59166821                     1602L                   SAYS LOCK S.L.
3     V59166251                     011HV        JOSE MARIA ONIEVA SANCHEZ
4     V59166241                     010HJ  JOSE FRANCISCO GARC÷A FERNµNDEZ

### 🐍 Me quedo exclusivamente con los expedientes que tienen un único profesional

In [8]:
conteo_expedientes = df_servicios['N. Expediente'].value_counts()
expedientes_unicos = conteo_expedientes[conteo_expedientes == 1].index
df_expedientes_unicos = df_servicios[df_servicios['N. Expediente'].isin(expedientes_unicos)]
df_expedientes_unicos.head()

   N. Expediente CÛd. profesional asignado    Nombre del proveedor asignado
1      V59166961                     9506X                 AVILA & GO, S.L.
2      V59166821                     1602L                   SAYS LOCK S.L.
4      V59166241                     010HJ  JOSE FRANCISCO GARC÷A FERNµNDEZ
8      V59164311                     6102K           HRISTO TODOROV HRISTOV
10     V59164231                     0112G             JAIME RAMIREZ GARCIA

In [9]:
# Cuento los registros con un único profesional
registros_con_servicios = df_expedientes_unicos['N. Expediente'].count()
print(f"Total Encuestas: {registros_con_servicios}")

Total Encuestas: 588587

### 🐍 Cruzo la información con el fichero de Medalia que ya tienen el cruce con Peritos

In [10]:
df['ES - General Claim - File Number'] = df['ES - General Claim - File Number'].astype(str)
df_expedientes_unicos['N. Expediente'] = df_expedientes_unicos['N. Expediente'].astype(str)
df_medalia_peritos_servicios = pd.merge(df_medalia_peritos, df_expedientes_unicos, how='left', left_on='ES - General Claim - File Number', right_on='N. Expediente')
df_medalia_peritos_servicios.head()

,ES - Client first name,ES - Client last name,Email,ES - Client ID,ES - Phone number,ES - Province,ES - Touchpoint,ES - MAPFRE Santander Record,Export AT Description,ES - Unit ID Text,ES - Unit ID,ES - Agent,Fecha de respuesta,ES - NPS including Corredores,ES - Corredores - Verbatim Comment including Corredores,ES - Policy number,ES - Contact Intrest including Corredores,ES - General Claim - Type of claim Descripction,ES - General Claim - File Number,ES - General Claim - Processor Name,ES - Home - Number repair Services,ES - Home - Activity Repair Code,ES - Home - Risk Address Town,ES - Home - Risk Address Province,ES - Home - Risk Address Postal Code,ES- Motivo de valoración - Hogar - Corredores,"ES - Centro Tramitador Hogar, Multirriesgo",ES - Home - Satisfaction Repairers Service including Corredores,ES - Home - Satisfaction Claim Management including Corredores,ES - Home - Satisfaction Information including Corredores,ES - Home - Satisfaction Proactivity including Corredores,ES - Home - Satisfaction Communication including Corredores,ES - Home - Satisfaction Repair Quality including Corredores,¿Has conseguido contactar con el cliente?,¿El cliente queda conforme?,Observaciones,Indique el motivo de insatisfacción detectado en el asegurado:,Indique la propuesta ofrecida al asegurado,"Si ha seleccionado 'Otros', por favor especifique cuál",oficina,Código DGT,Número Expediente Operacional,Código Profesional,Nombre Profesional,Nº de profesionales distintos por expte,N. Expediente,CÛd. profesional asignado,Nombre del proveedor asignado
0,Leandro,Casamitjana Rossello,lpm828@hotmail.com,31214918,608724208.0,BARCELONA,Prestación Hogar,No,CATALUÑA NORTE,mapfre_es_5529,Delegacion Artes,5283864,2026-01-01 09:18:43,0,Hoy a 1 de enero de 2026 ningun operació ha ve...,732200197580,Sí,BRICOLAJE EN EL HOGAR,V55660291,ANA BELEN CUNTIN PEREZ,1.0,01,Navas,BARCELONA,8670.0,Resolución del siniestro,CMP Reparables,NaN,NaN,NaN,NaN,NaN,NaN,Otro motivo,Sí,CORRESPOPNDE V55662061,Otros,NaN,NaN,5529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Graciela,Chetrit Russi,gracielaches@yahoo.es,11515548,629721064.0,GIRONA,Prestación Hogar,No,CATALUÑA NORTE,mapfre_es_1773,Delegacion Girona Urb. Xavier Cugat,170776,2026-01-01 09:22:02,10,"La atencion recibida , y la buena resolucion .",730880036859,NaN,ROBO,V56213511,OLGA DE LA MORENA BRIONES,1.0,16,Girona,GIRONA,17003.0,Resolución del siniestro,CMP Reparables,9.0,9.0,9.0,9.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,1773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jose Antonio,Merino Martin,jmerinom@telefonica.net,445728,626363401.0,MADRID,Prestación Hogar,No,MADRID SUR,mapfre_es_6713,Delegacion Coslada Argentina,5270757,2026-01-01 09:23:53,10,Personal muy profesional y resolutivo.,732200074430,NaN,BRICOLAJE EN EL HOGAR,V56017561,PIEDAD ASENSIO,1.0,02,San Fernando De Henares,MADRID,28830.0,Intervención de los reparadores,CMP Reparables,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sí,NaN,NaN,NaN,NaN,6713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Maria Jesus,De Lorenzo Garcia,mj_lorengar@yahoo.es,19715949,627036490.0,MADRID,Prestación Hogar,No,MADRID SUR,mapfre_es_6183,Delegacion Madrid Paseo Pontones,5281192,2026-01-01 09:48:25,9,NaN,732300146131,NaN,AGUA,V52830341,NURIA RUIZ BLANCO,3.0,01||03||04,Madrid,MADRID,28005.0,Resolución del siniestro,CMP Reparables,9.0,9.0,NaN,9.0,9.0,9.0,NaN,Desconocido (no contacto),NaN,NaN,NaN,NaN,6183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Lourdes,Palacios Martin,lourpalacios@gmail.com,35310782,646516388.0,VIZCAYA,Prestación Hogar,No,SALAMANCA,mapfre_es_5754,Delegacion Ciudad Rodrigo,370934,2026-01-01 09:50:19,10,NaN,732300326228,NaN,CRISTALES / ROTURAS,V56174001,RAQUEL MORENO ALONSO(GSS-ROTURAS),1.0,VT,Bilbao,VIZCAYA,48004.0,Cobro de indemnización,CMP Reparables,10.0,10.0,10.0,10.0,10.0,10.0,NaN,Sí,NaN,NaN,NaN,NaN,5754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
registros_despues_union_servicios = df_medalia_peritos_servicios['ES - Client ID'].count()
print(f"Total Encuestas: {registros_despues_union_servicios}")

Total Encuestas: 29915

In [12]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
df_tsr = pd.read_excel(r'Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\NPS_Hogar\Tablas\TSR.xlsx')
df_tsr.head()

,COD_POSTAL,PROV,COD_ZONA,NIVEL_2,TSR,NIVEL_E,CTT
0,28850,28,I3,J1,Juan Francisco Berrio Díaz,1,01 Madrid
1,28851,28,I3,J1,Juan Francisco Berrio Díaz,1,01 Madrid
2,28860,28,IE,J1,Juan Francisco Berrio Díaz,1,01 Madrid
3,28814,28,IE,J1,Juan Francisco Berrio Díaz,1,01 Madrid
4,28815,28,IE,J1,Juan Francisco Berrio Díaz,1,01 Madrid

In [13]:
# Convertir 'ES - Home - Risk Address Postal Code' a numérico sin decimales, manejando errores
df_medalia_peritos_servicios['ES - Home - Risk Address Postal Code'] = pd.to_numeric(
    df_medalia_peritos_servicios['ES - Home - Risk Address Postal Code'], errors='coerce'
).fillna(0).astype(int)
# Convertir 'COD_POSTAL' a numérico sin decimales, manejando errores
df_tsr['COD_POSTAL'] = pd.to_numeric(
    df_tsr['COD_POSTAL'], errors='coerce'
).fillna(0).astype(int)
df_medalia_peritos_servicios_tsr = pd.merge(df_medalia_peritos_servicios, df_tsr, how='left', left_on='ES - Home - Risk Address Postal Code', right_on='COD_POSTAL')
df_medalia_peritos_servicios_tsr.head()

,ES - Client first name,ES - Client last name,Email,ES - Client ID,ES - Phone number,ES - Province,ES - Touchpoint,ES - MAPFRE Santander Record,Export AT Description,ES - Unit ID Text,ES - Unit ID,ES - Agent,Fecha de respuesta,ES - NPS including Corredores,ES - Corredores - Verbatim Comment including Corredores,ES - Policy number,ES - Contact Intrest including Corredores,ES - General Claim - Type of claim Descripction,ES - General Claim - File Number,ES - General Claim - Processor Name,ES - Home - Number repair Services,ES - Home - Activity Repair Code,ES - Home - Risk Address Town,ES - Home - Risk Address Province,ES - Home - Risk Address Postal Code,ES- Motivo de valoración - Hogar - Corredores,"ES - Centro Tramitador Hogar, Multirriesgo",ES - Home - Satisfaction Repairers Service including Corredores,ES - Home - Satisfaction Claim Management including Corredores,ES - Home - Satisfaction Information including Corredores,ES - Home - Satisfaction Proactivity including Corredores,ES - Home - Satisfaction Communication including Corredores,ES - Home - Satisfaction Repair Quality including Corredores,¿Has conseguido contactar con el cliente?,¿El cliente queda conforme?,Observaciones,Indique el motivo de insatisfacción detectado en el asegurado:,Indique la propuesta ofrecida al asegurado,"Si ha seleccionado 'Otros', por favor especifique cuál",oficina,Código DGT,Número Expediente Operacional,Código Profesional,Nombre Profesional,Nº de profesionales distintos por expte,N. Expediente,CÛd. profesional asignado,Nombre del proveedor asignado,COD_POSTAL,PROV,COD_ZONA,NIVEL_2,TSR,NIVEL_E,CTT
0,Leandro,Casamitjana Rossello,lpm828@hotmail.com,31214918,608724208.0,BARCELONA,Prestación Hogar,No,CATALUÑA NORTE,mapfre_es_5529,Delegacion Artes,5283864,2026-01-01 09:18:43,0,Hoy a 1 de enero de 2026 ningun operació ha ve...,732200197580,Sí,BRICOLAJE EN EL HOGAR,V55660291,ANA BELEN CUNTIN PEREZ,1.0,01,Navas,BARCELONA,8670,Resolución del siniestro,CMP Reparables,NaN,NaN,NaN,NaN,NaN,NaN,Otro motivo,Sí,CORRESPOPNDE V55662061,Otros,NaN,NaN,5529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8670,8,H5,T9,Jordi Calafell Pérez,2,02 Cataluña Baleares
1,Graciela,Chetrit Russi,gracielaches@yahoo.es,11515548,629721064.0,GIRONA,Prestación Hogar,No,CATALUÑA NORTE,mapfre_es_1773,Delegacion Girona Urb. Xavier Cugat,170776,2026-01-01 09:22:02,10,"La atencion recibida , y la buena resolucion .",730880036859,NaN,ROBO,V56213511,OLGA DE LA MORENA BRIONES,1.0,16,Girona,GIRONA,17003,Resolución del siniestro,CMP Reparables,9.0,9.0,9.0,9.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,1773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17003,17,H6,LS,Joan Pau Alberti Sánchez,2,02 Cataluña Baleares
2,Jose Antonio,Merino Martin,jmerinom@telefonica.net,445728,626363401.0,MADRID,Prestación Hogar,No,MADRID SUR,mapfre_es_6713,Delegacion Coslada Argentina,5270757,2026-01-01 09:23:53,10,Personal muy profesional y resolutivo.,732200074430,NaN,BRICOLAJE EN EL HOGAR,V56017561,PIEDAD ASENSIO,1.0,02,San Fernando De Henares,MADRID,28830,Intervención de los reparadores,CMP Reparables,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sí,NaN,NaN,NaN,NaN,6713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28830,28,IO,KF,Daniel Lara Ahijón,1,01 Madrid
3,Maria Jesus,De Lorenzo Garcia,mj_lorengar@yahoo.es,19715949,627036490.0,MADRID,Prestación Hogar,No,MADRID SUR,mapfre_es_6183,Delegacion Madrid Paseo Pontones,5281192,2026-01-01 09:48:25,9,NaN,732300146131,NaN,AGUA,V52830341,NURIA RUIZ BLANCO,3.0,01||03||04,Madrid,MADRID,28005,Resolución del siniestro,CMP Reparables,9.0,9.0,NaN,9.0,9.0,9.0,NaN,Desconocido (no contacto),NaN,NaN,NaN,NaN,6183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28005,28,0L,ST,Ambrosio Benito Navas,1,01 Madrid
4,Lourdes,Palacios Martin,lourpalacios@gmail.com,35310782,646516388.0,VIZCAYA,Prestación Hogar,No,SALAMANCA,mapfre_es_5754,Delegacion Ciudad Rodrigo,370934,2026-01-01 09:50:19,10,NaN,732300326228,NaN,CRISTALES / ROTURAS,V56174001,RAQUEL MORENO ALONSO(GSS-ROTURAS),1.0,VT,Bilbao,VIZCAYA,48004,Cobro de indemnización,CMP Reparables,10.0,10.0,10.0,10.0,10.0,10.0,NaN,Sí,NaN,NaN,NaN,NaN,5754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48004,48,C1,JH,Garikoitz Arrieta Goiri,4,04 Norte

In [14]:
total_registros_final = df_medalia_peritos_servicios_tsr['ES - Client ID'].count()
print(f"Total Encuestas: {total_registros_final}")

Total Encuestas: 29915

In [15]:
df_medalia_peritos_servicios_tsr.to_excel(r'Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\NPS_Hogar\nps_hogar.xlsx', index=False)
print("■"*80)
print("  El fichero del NPS de Siniestros Hogar se ha exportado correctamente")
print("■"*80)

■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  El fichero del NPS de Siniestros Hogar se ha exportado correctamente
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

In [17]:
df1 = pd.read_excel(r'Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\NPS_Hogar\nps_hogar.xlsx')

# Nos quedamos unicamente con las columnas que contienen el id y el comentario
df = df1[
    [
        "ES - General Claim - File Number",
        "ES - Corredores - Verbatim Comment including Corredores"
    ]
].copy()

# Eliminamos las filas que no tienen comentario
df = df[
    df["ES - Corredores - Verbatim Comment including Corredores"].notna() &
    (df["ES - Corredores - Verbatim Comment including Corredores"].str.strip() != "")
]

# Rseteamos los indices
df = df.reset_index(drop=True)

print("Filas totales:", len(df1))
print("Filas con texto:", len(df))

Filas totales: 29915
Filas con texto: 12661

In [ ]:
# Diccionario de aspectos
aspectos_dic = {
    "tiempo": [
        "rapido", "rapidez", "tardar", "esperar", "demora", "celeridad", "tardo", "inmediatez", "dilacion", "prontitud",
        "puntualidad", "plazo", "urgente", "lento", "agilidad", "urgencia", "rapidisimo", "retraso"
    ],

    "calidad_trabajo": [
        "profesional", "profesionalidad", "eficaz", "eficiencia", "eficiente", "destreza", "chapucero",
        "calidad", "correcto", "bien", "experiencia", "sustracción", "eficacia", "efectividad",
        "chapuza", "defecto", "mal", "praxis", "efectivo", "resolutivo"
    ],

    "trato_cliente": [
        "amable", "amabilidad", "trato", "atencion", "adavle", "proactividad", "respetuoso", "cuidadoso", "maravilloso", "cercanía", "atento",
        "educado", "cordial", "empatia", "servicial", "diligencia", "diligente", "encantador", "empático", "simpático", "agradable", "implicación"
    ],

    "gestion_comunicacion": [
        "comunicacion", "informacion", "llamada", "contacto", "contestación", "aplicacion", "telefónica",
        "seguimiento", "respuesta", "explicacion", "avisar", "teléfono", "sms", "mail", "email",
        "aplicacion", "app", "mensaje", "tramitación", "web", "llamar", "correo", "online"
    ],

    "resultado": [
        "solucion", "resolver", "arreglar", "reparar", "reparado", "concluido", "solucionar",
        "finalizado", "terminado", "pendiente", "finalizar", "terminar", "resolución",
        "sin resolver", "no arreglado", "resuelto", "concluir", "acabado", "solventar"
    ],

    "indemnizacion": [
        "indemnizacion", "pago", "abono", "transferencia", "indernizacion", "indenizacion", "cobro",
        "reembolso", "compensacion", "tasacion", "cantidad", "devolución", "reembolso", "compensación",
        "importe", "cobrar", "insuficiente", "bancario", "tasación", "cuantía"
    ],

    "cobertura": [
        "cobertura", "poliza", "incluido", "cubrir", "incluir", "cubierto", "entrar", "cubre",
        "excluido", "condiciones", "garantia", "no cubrir", "cubrio", "exclusión", "incluido"]}

In [21]:
# Normalizamos el texto
import re

def normalizar_texto(texto):
    if not isinstance(texto, str):
        return ""
    texto = texto.lower()
    texto = re.sub(r"\s+", " ", texto)
    return texto


# función de ventana
def extraer_fragmento_local(texto, palabra, ventana=50):
    texto = normalizar_texto(texto)

    idx = texto.find(palabra)
    if idx == -1:
        return None

    inicio = max(0, idx - ventana)
    fin = min(len(texto), idx + len(palabra) + ventana)

    fragmento = texto[inicio:fin]

    # Ajustar bordes a palabra completa
    if inicio > 0:
        primer_espacio = fragmento.find(" ")
        if primer_espacio != -1:
            fragmento = fragmento[primer_espacio + 1:]

    if fin < len(texto):
        ultimo_espacio = fragmento.rfind(" ")
        if ultimo_espacio != -1:
            fragmento = fragmento[:ultimo_espacio]

    fragmento = fragmento.strip(" ,.;:-")

    return fragmento.strip()

def unir_fragmentos(fragmentos):
    """
    Une varios fragmentos en uno solo manteniendo el orden
    """
    if not fragmentos:
        return None

    # eliminar duplicados manteniendo orden
    fragmentos = list(dict.fromkeys(fragmentos))

    # unir como texto continuo
    texto_unido = " ... ".join(fragmentos)

    return texto_unido

# función principal
def obtener_fragmentos_por_aspecto(texto, dic_aspectos):
    resultado = {}

    for aspecto, palabras in dic_aspectos.items():
        fragmentos = []

        for p in palabras:
            frag = extraer_fragmento_local(texto, p)
            if frag:
                fragmentos.append(frag)

        if fragmentos:
            fragmento_unico = unir_fragmentos(fragmentos)
            resultado[aspecto] = fragmento_unico

    return resultado

df["fragmentos_por_aspecto"] = df["ES - Corredores - Verbatim Comment including Corredores"].apply(
    lambda x: obtener_fragmentos_por_aspecto(x, aspectos_dic))

In [23]:
# Cargamos el modelo de analisis de sentimiento
import joblib
model = joblib.load("modelo_sentimiento_hogar_logreg.pkl")
vectorizer = joblib.load("tfidf_vectorizer_hogar.pkl")

# Limpiamos el texto
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

stop_words = set(stopwords.words("spanish"))

def limpiar_para_modelo(texto):
    texto = texto.lower()
    texto = texto.translate(str.maketrans('', '', string.punctuation))
    tokens = word_tokenize(texto)
    tokens = [t for t in tokens if t not in stop_words and len(t) > 2]
    return " ".join(tokens)

# Predicción de sentimiento
def predecir_sentimiento(texto):
    texto_limpio = limpiar_para_modelo(texto)
    vec = vectorizer.transform([texto_limpio])
    return model.predict(vec)[0]

# genera TODAS las columnas basadas en el diccionario
def aspectos_a_columnas(dic_fragmentos):
    resultado = {}

    for aspecto in aspectos_dic.keys():  
        fragmento = dic_fragmentos.get(aspecto, None)

        if fragmento:
            resultado[aspecto] = predecir_sentimiento(fragmento)
        else:
            resultado[aspecto] = ""   

    return resultado

# Aplicar
df["aspectos_tmp"] = df["fragmentos_por_aspecto"].apply(aspectos_a_columnas)

# Expandir a columnas
df_aspectos = df["aspectos_tmp"].apply(pd.Series)

# Unir al dataframe original
df = pd.concat([df, df_aspectos], axis=1)

# Eliminar columna temporal
df.drop(columns=["aspectos_tmp"], inplace=True)

In [25]:
# Lista de columnas de aspectos (basada en tu diccionario)
columnas_aspectos = list(aspectos_dic.keys())

df1 = df1.merge(
    df[
        ["ES - General Claim - File Number"] + columnas_aspectos
    ],
    on="ES - General Claim - File Number",
    how="left")

In [26]:
df1.to_excel(r"Z:\00 COMUN PRESTACIONES Y PROVEEDORES\NPS_POWER_BI\Copias\00_NPS\Pruebas\Hogar\nps_hogar_aspecto_sentimiento.xlsx", index=False)